<div
  class="
    border-[1px]
    w-full
    md:w-auto
    py-2
    rounded-full
    shadow-sm
    hover:shadow-md
    transition
    cursor-pointer
  "
>
  <div
    class="
      flex
      flex-row
      items-center
      justify-between
    "
  >
    <div
      class="
        text-sm
        font-semibold
        px-6
      "
    >
        Cualquier lugar
    </div>
    <div
      class="
        hidden
        sm:block
        text-sm
        font-semibold
        px-6
        border-x-[1px]
        flex-1
        text-center
      "
    >
        Cualquier semana
    </div>
    <div
      class="
        text-sm
        pl-6
        pr-2
        text-gray-600
        flex
        flex-row
        items-center
        gap-3
      "
    >
      <div class="hidden sm:block">¿Cuántos huéspedes?</div>
      <div
        class="
          p-2
          bg-rose-500
          rounded-full
          text-white
        "
      >
        <x-icon.search class="size-[18px]" />
      </div>
    </div>
  </div>
</div>
